version: '3.8'

services:
  web:
    container_name: people-power
    image: people-dev:2.1.4
    build: .
    command: yarn dev
    ports: 
     - 8000:3000
     - 8080:80
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - CLOUDINARY_ENVIRONMENT=${CLOUDINARY_ENVIRONMENT}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - FX_ACCESS_KEY=${FX_ACCESS_KEY}
      - MAILJET_KEY=${MAILJET_KEY}
      - MAILJET_SECRET=${MAILJET_SECRET}
    links:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
